server:
  port: 1014
spring:
  application:
    name: jacksoon-console
  datasource:
    url: jdbc:postgresql://localhost:5432/jacksoon_console
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
filter:
  server:
    url: ${FILTER_SERVER_URL:http://localhost:1011/filter}

metric:
  directory: ${METRIC_DIRECTORY:D:/jacksoon/metric}
