spring:
  application:
    name: jacksoon-console
  port: 1014
  datasource:
    url: jdbc:postgresql://localhost:5432/jacksoon_console
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
