package io.jacksoon.router.produce.dto;

public enum RouterFailureType {
    INVALID_REQUEST,
    FILTER_EXECUTION_FAILED,
    ROUTE_NOT_FOUND,
    SERVICE_NOT_FOUND,
    BACKEND_POOL_NOT_FOUND,
    BACKEND_UNAVAILABLE,
    CONNECTION_FAILED,
    CONNECTION_TIMEOUT,
    BACKEND_RESPONSE_FAILED,
    CLIENT_CONNECTION_CLOSED,
    INTERNAL_ERROR
}